"""empty message

Revision ID: 442d9284c5be
Revises: b04c31588b1c
Create Date: 2025-03-13 08:55:58.415185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442d9284c5be'
down_revision = 'b04c31588b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_patients', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_patients', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
